### ISSUE TITLE
Is there a way to get the value of all declared constans inside units imported in the current unit

### ISSUE THREAD

**Issue by EduardoVaz06** [integrated-application-development/sonar-delphi#286]
### Prerequisites

- [X] This question has not already been answered.
- [X] This question is about SonarDelphi, not SonarQube or Delphi.

### Inquiry

Hello!

I am currently working on a custom rule for our company’s business logic, but I've encountered a challenge that got me stuck.

The rule is designed to identify any WM_ (Windows Message) constants with duplicate values across the current unit and all units imported by it.

I was able to reach the constant declarations but not their value in imported units.

The steps I followed:

1. Visited the DelphiAst
  * `public DelphiCheckContext visit(DelphiAst delphiAst, DelphiCheckContext context`
2. Got all UsesClauseNode
  * `for (UsesClauseNode usesClauseNode : delphiAst.findDescendantsOfType(UsesClauseNode.class))`
3. Got all ImportedUnits inside each UsesClauseNode
  * `for (UnitImportNode importedUnit : usesClauseNode.getImports())`

While debugging, I managed to access VariableNameDeclarationImpl objects using:

`importedUnit.getImportNameDeclaration().getUnitScope().getVariableDeclarations()`

This provided me with the constant names (e.g., Variable: image = 'WM_EXAMPLE'), but I couldn't find a way to get its value. 

![image](https://github.com/user-attachments/assets/261331d5-6910-47f3-b6e7-f48719a09f9d)
![image](https://github.com/user-attachments/assets/f1a94240-78c1-453f-bcb9-9969e848d25a)

My question is: Is there any way I get the constant value from a VariableNameDeclaration? Or maybe a different way to reach the constants declared in the units imported in the current unit.

Thanks!

**Comment by zaneduffield** [comment]
Constant evaluation is not yet implemented, see #116.

**Comment by fourls** [comment]
> The rule is designed to identify any WM_ (Windows Message) constants with duplicate values across the current unit and all units imported by it.

As @zaneduffield says, this rule isn't possible without constant evaluation, since the values of constant expressions don't get saved in the symbol table.

> Is there any way I get the constant value from a VariableNameDeclaration?

From a `VariableNameDeclaration`, no, since it's a symbol table object and is disconnected from the actual code. However, you can get the expression from the `ConstDeclarationNode` via `ConstDeclarationNode::getExpression`. This means that you could implement a simpler version that only compares `WM_` constants within the same unit (although I admit it would be less useful).

To do this, my approach would be to add a `List<ConstDeclarationNode>` field on your check class, then:

* Inside `visit(ConstDeclarationNode)`:
    1. Add the node to the list
* Inside `visit(DelphiAst)`:
    1. At the start of the method, visit all children of the AST by calling `super.visit(ast, context)`
    2. Getting the expression of the const declaration nodes in the list via `ConstDeclarationNode::getExpression`
    3. Where the expression is `IntegerLiteralNode`, get the integer value via `IntegerLiteralNode::getValue`
    4. Compare with the other const declaration nodes in the list and see if any have the same integer value
    5. Clear the list
    6. Return `data` instead of calling `super.visit` as usual

Even if your `WM_` constant expressions are more complex, if they're generally consistent you could adjust the expression handling to get useful values out of more complicated cases.

**Comment by EduardoVaz06** [comment]
Got it, thanks for the answer!

One other thing, if it was a Variable not a constant, or other kind, would I be able to do this?

And about the issue https://github.com/integrated-application-development/sonar-delphi/issues/286, it covers the functionality I described or should I open another one requesting something similar?

**Comment by zaneduffield** [comment]
You can also add a visitor for `VarDeclarationNode` and collect those items into a separate list.
The only thing to be careful of there is to check the scope of the var declaration.

e.g.
```java
if (node.getScope() instanceof UnitScope) {
  ...
}
```

Oh, and you would might need to handle the case where the global var isn't initialised inline.

I presume you meant to link to #116 and not #286 (this issue), if so then yes, that issue does cover the fundamental functionality you require.
